repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: requirements-txt-fixer

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black tkww-de-take-home-test tests
        language: system
        types:
          - python
      - id: flake8
        name: flake8
        entry: poetry run flake8 tkww-de-take-home-test tests
        language: system
        types:
          - python
      - id: isort
        name: isort
        entry: poetry run isort --profile black tkww-de-take-home-test tests
        language: system
        types:
          - python
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types:
          - python
      - id: tests
        name: tests
        language: system
        entry: poetry run pytest tests
        types:
          - python
        stages:
          - push
        pass_filenames: false
